### ISSUE TITLE
"Spiel suchen" funktioniert nicht

### ISSUE THREAD

**Issue by akramer-zibra** [PascalS86/wordclash#4]
...leider weder im FF 42 noch Chrome  46.0.2490.86 m (64-bit)

Hab mir einen registrierten Nutzer gemacht. Login hat funktioniert.

Liegt es vielleicht daran, dass ich mit einem account keine "2 Spieler" simulieren kann?!

**Comment by PascalS86** [comment]
Migrations wurde nicht durchgeführt
